[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x56d364"
magenta = "0xbc8cff"
red = "0xffa198"
white = "0xb1bac4"
yellow = "0xe3b341"

[colors.cursor]
cursor = "0xe6edf3"
text = "0x30363d"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xb1bac4"
yellow = "0xd29922"

[colors.primary]
background = "0x30363d"
foreground = "0xe6edf3"
